name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: make
        run: make
      - name: make clean
        run: make clean
      - name: make fclean
        run: make ; make fclean
      - name: make re
        run: make re